inside init
starting connection
failed to connect to 
